### ISSUE TITLE
Numix Website Donation Button cannot be clicked because of screen resolution

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numixproject.github.io#12]
I noticed that now that there is a link button to the new Numix blog on the Numix Project website, the "Donate to support us" button cannot be clicked anymore because the downwards arrows are covering that area.

Screenshot (Ubuntu 14.10, Firefox, same e.g. with Chromium):

![numix_website](https://cloud.githubusercontent.com/assets/7164227/5991800/3b76a0ca-aa07-11e4-8d0a-e7b0c6ebec4a.png)

This appears to be related to the screen resolution. My screen resolution (max) is 1280x800. If the browser window is made smaller, then even the "Visit our official blog" button cannot be clicked anymore. I figure that a screen resolution of 1280x800 is not completely obsolete yet, and without Ubuntu Unity's Global Menu the vertical space would be even smaller.

Maybe it is a possibility to place either these links (Blog, Donation) or the downwards arrows somewhat to the side, so that they do not interfere with each other.

Ah, I just noticed that I can still click on the Donation "button" when I go to the very edges of the text, because the downwards arrows only cover the central area. But that was hard to figure out, and it should not be so difficult to locate the Numix Donation link :-)

**Comment by satya164** [comment]
Fixed in be02c0d632a009fcae680f8e96a48856715cc4ee
