### ISSUE TITLE
Donations dialog box allows for donations in negative( like -$3)

### ISSUE THREAD

**Issue by AnuragKumar99** [numixproject/numixproject.github.io#14]
It shouldn't go down a particular(whatever you like) value. Definitely not below 0! I am unable to understand the pattern validator applied in line 105 of index.html
<input type="number" name="amount" value="5.00" pattern="\d+(\.\d{2})?" oninvalid="setCustomValidity('Please enter a valid currency')" onchange="try{setCustomValidity('')}catch(e){}" autofocus>

But I believe a min attribute should do the job.

**Comment by PaoloRotolo** [comment]
@satya164
