### ISSUE TITLE
https://numixproject.org/ broken

### ISSUE THREAD

**Issue by orschiro** [numixproject/numixproject.github.io#20]
I want to make you aware of this:

![image](https://user-images.githubusercontent.com/170947/34560804-a29306f6-f147-11e7-82d6-cd529c45077d.png)

**Comment by Foggalong** [comment]
We're working on it :)

**Comment by strafe** [comment]
@Foggalong is there any update on this? It's now parked.

**Comment by Foggalong** [comment]
Yeah I've tried setting up redirects and it just hasn't worked so far. When I've got a spare afternoon I'm going to sitdown and sort all the domain stuff out across a few different projects but atm I'm stuck sorting out business paperwork to do with HMRC and CH :cry:

**Comment by strafe** [comment]
Gotcha, I was mostly missing http://croma.numixproject.org, I hadn't read the updated README until just now, unfortunate the project won't be maintained/hosted anymore. Do you have any recommendations for other similar web apps (I mostly used to to general a palette of sorts from a single colour), for now I've been using http://paletton.com.

**Comment by Foggalong** [comment]
Paletton is what I personally use too 😀

**Comment by Foggalong** [comment]
Fixed, turns out it was a problem on domain.com's end which I didn't find out until in the process of switching to a new registrar :facepalm:
