### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numixproject.github.io#7]
We seem to be missing error pages. The basics should be covered.
- [ ] 400: Bad Request
- [ ] 403: Forbidden Page
- [ ] 404: Page Not Found
- [ ] 418: I'm a teapot
- [ ] 500: Internal Error

**Comment by Foggalong** [comment]
The 404 page doesn't actually work if you're on the main Numix site, only on the GitHub pages version

**Comment by satya164** [comment]
We're not using GitHub pages, i think.

**Comment by Foggalong** [comment]
Normal Website - https://numixproject.org/pagethatdontexist
GitHub pages - https://numixproject.github.io/pagethatdontexist

**Comment by satya164** [comment]
What I said above ^.

**Comment by Foggalong** [comment]
Ohh, you mean using GitHub pages to serve the actual website? We shouldn't really be doing that anyway because it means the other error messages can't be displayed. Still, it's nice to have the pages as a backup URL

**Comment by satya164** [comment]
@Foggalong I didn't understand why we shouldn't be doing that.

But anyways, we have to setup a build service so that when we push any changes, the new changes get applied instantly.

**Comment by Foggalong** [comment]
Because a proper error page looks a lot nicer than the default of the web server. People will most likely be seeing a lot more of them now we have the store

**Comment by satya164** [comment]
@Foggalong GitHub pages supports showing these kinds of customized pages, AFAIK.

**Comment by Foggalong** [comment]
Last time I tried/checked the docs it only supported 404

**Comment by satya164** [comment]
Hmm...

Satyajit Sahoo
UX Designer
Behance Profile <https://www.behance.net/satyajitha28c7>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by Foggalong** [comment]
Seems 404 is the only supported one now :(
